version: '3'

volumes:
    logs:
        driver: local

services:
    # http://localhost:7700
    webserver:
        image: php:8-alpine
        container_name: universe
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 7700:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs

# docker-compose up -d